import { Channel } from "@/types/iptv";
import { v4 as uuidv4 } from "uuid";

export const mockChannels: Channel[] = [
  {
    id: uuidv4(),
    name: "BBC One",
    url: "https://example.com/bbc1.m3u8",
    logo: "https://via.placeholder.com/150?text=BBC1",
    group: "UK",
  },
  {
    id: uuidv4(),
    name: "BBC Two",
    url: "https://example.com/bbc2.m3u8",
    logo: "https://via.placeholder.com/150?text=BBC2",
    group: "UK",
  },
  {
    id: uuidv4(),
    name: "ITV",
    url: "https://example.com/itv.m3u8",
    logo: "https://via.placeholder.com/150?text=ITV",
    group: "UK",
  },
  {
    id: uuidv4(),
    name: "Channel 4",
    url: "https://example.com/channel4.m3u8",
    logo: "https://via.placeholder.com/150?text=CH4",
    group: "UK",
  },
  {
    id: uuidv4(),
    name: "Channel 5",
    url: "https://example.com/channel5.m3u8",
    logo: "https://via.placeholder.com/150?text=CH5",
    group: "UK",
  },
  {
    id: uuidv4(),
    name: "CNN",
    url: "https://example.com/cnn.m3u8",
    logo: "https://via.placeholder.com/150?text=CNN",
    group: "News",
  },
  {
    id: uuidv4(),
    name: "BBC News",
    url: "https://example.com/bbcnews.m3u8",
    logo: "https://via.placeholder.com/150?text=BBCNews",
    group: "News",
  },
  {
    id: uuidv4(),
    name: "Sky News",
    url: "https://example.com/skynews.m3u8",
    logo: "https://via.placeholder.com/150?text=SkyNews",
    group: "News",
  },
  {
    id: uuidv4(),
    name: "ESPN",
    url: "https://example.com/espn.m3u8",
    logo: "https://via.placeholder.com/150?text=ESPN",
    group: "Sports",
  },
  {
    id: uuidv4(),
    name: "Sky Sports",
    url: "https://example.com/skysports.m3u8",
    logo: "https://via.placeholder.com/150?text=SkySports",
    group: "Sports",
  },
  {
    id: uuidv4(),
    name: "BT Sport",
    url: "https://example.com/btsport.m3u8",
    logo: "https://via.placeholder.com/150?text=BTSport",
    group: "Sports",
  },
  {
    id: uuidv4(),
    name: "Disney Channel",
    url: "https://example.com/disney.m3u8",
    logo: "https://via.placeholder.com/150?text=Disney",
    group: "Kids",
  },
  {
    id: uuidv4(),
    name: "Nickelodeon",
    url: "https://example.com/nickelodeon.m3u8",
    logo: "https://via.placeholder.com/150?text=Nick",
    group: "Kids",
  },
  {
    id: uuidv4(),
    name: "Cartoon Network",
    url: "https://example.com/cartoonnetwork.m3u8",
    logo: "https://via.placeholder.com/150?text=CN",
    group: "Kids",
  },
  {
    id: uuidv4(),
    name: "HBO",
    url: "https://example.com/hbo.m3u8",
    logo: "https://via.placeholder.com/150?text=HBO",
    group: "Movies",
  },
  {
    id: uuidv4(),
    name: "Sky Movies",
    url: "https://example.com/skymovies.m3u8",
    logo: "https://via.placeholder.com/150?text=SkyMovies",
    group: "Movies",
  },
];